### ISSUE TITLE
No auth in MQTT

### ISSUE THREAD

**Issue by marksev1** [jamiehoward430/mycroft-mymqtt#1]
I have this problem
MyMQTTSkill
Traceback (most recent call last):
  File "/home/msev/mycroft-core/mycroft/skills/core.py", line 200, in receive_handler
    handler(message)
  File "/home/msev/mycroft-core/mycroft/skills/MyMQTT/__init__.py", line 49, in handle_single_command
    mqttc.connect(self.mqtthost,self.mqttport)
  File "/home/msev/.virtualenvs/mycroft/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/home/msev/.virtualenvs/mycroft/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
error: getaddrinfo() argument 2 must be integer or string

The mqtt-user and mqtt-pass i left empty "" , like this. I think that is the problem.

**Comment by marksev1** [comment]
Any feedback? I tried commenting out the user and password parts and it still didn't work...dunno what i'm doing wrong...

**Comment by marksev1** [comment]
Problem solved was a conf problem i will post PR later to the readme :D
